resources:
  Dbp\Relay\NexusBundle\Entity\Something:
    types: ['https://schema.org/Something']
    shortName: "NexusSomething"
    normalizationContext:
      groups: ["NexusSomething:output"]
    denormalizationContext:
      groups: ["NexusSomething:input"]
    operations:
      ApiPlatform\Metadata\Get:
        provider: Dbp\Relay\NexusBundle\State\SomethingProvider
        uriTemplate: "/nexus/somethings/{identifier}"
        openapiContext:
          tags: ["Template"]
      ApiPlatform\Metadata\GetCollection:
        provider: Dbp\Relay\NexusBundle\State\SomethingProvider
        uriTemplate: "/nexus/somethings"
        openapiContext:
          tags: ["Template"]
      ApiPlatform\Metadata\Post:
        processor: Dbp\Relay\NexusBundle\State\SomethingProcessor
        uriTemplate: "/nexus/somethings"
        openapiContext:
          tags: ["Template"]
      ApiPlatform\Metadata\Delete:
        processor: Dbp\Relay\NexusBundle\State\SomethingProcessor
        uriTemplate: "/nexus/somethings/{identifier}"
        openapiContext:
          tags: ["Template"]
    properties:
      identifier:
        identifier: true
      name:
        iri: 'https://schema.org/name'
