services:
    Dbp\Relay\NexusBundle\Service\:
        resource: "../../Service"
        autowire: true
        autoconfigure: true

    Dbp\Relay\NexusBundle\Command\:
        resource: "../../Command"
        autowire: true
        autoconfigure: true

    Dbp\Relay\NexusBundle\TypesenseProxy\:
        resource: "../../TypesenseProxy"
        autowire: true
        autoconfigure: true

    Dbp\Relay\NexusBundle\Authorization\:
        resource: "../../Authorization"
        autowire: true
        autoconfigure: true
